# Generated by Django 4.1.3 on 2023-01-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioButtonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
            ],
        ),
    ]
