# Generated by Django 4.1.3 on 2023-01-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0002_radiobuttonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemodel',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toyapp.radiobuttonmodel'),
        ),
    ]
